Repository GenomicMedLab/wags-tails, pull requests merged in 2024-12, with the labels that each got.

#61 feat: add `MoaData` import to `__init__.py`
  src/wags_tails/__init__.py
Labels: enhancement, priority:low

#59 feat: add CLI
  README.md
  docs/source/cli_reference.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/reference/api/sources/wags_tails.moa.rst
  docs/source/usage.rst
  pyproject.toml
  src/wags_tails/cli.py
Labels: priority:low

#62 docs: fix CLI command name
  docs/source/cli_reference.rst
Labels: priority:low

#64 chore!: rename optional dependency
  .github/workflows/checks.yaml
  pyproject.toml
Labels: chore, priority:low
